/* AUTOGENERATED FILE - DO NOT EDIT CONTENTS */

export const projectId = "eiruzugttnsoabegmjwp"
export const publicAnonKey = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImVpcnV6dWd0dG5zb2FiZWdtandwIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NjAwMzk2ODcsImV4cCI6MjA3NTYxNTY4N30.PSc70SJlQZSTMSpCPbUOPsLurfvo-z4q-aCE65UB8-s"